// sahlearn-api/src/utils/pdf.js
const PDFDocument = require('pdfkit');

const BRAND = '#068562';
const DARK = '#011F28';
const GREY = '#506860';
const LIGHT = '#EDF4F2';

const STATUS_LABEL = { present: 'Present', late: 'Late', excused: 'Excused', absent: 'Absent' };

// Pipe a finished PDFDocument to res with correct headers
const sendPDF = (res, doc, filename) => {
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
  doc.pipe(res);
};

// ── Header bar ──────────────────────────────────────────────────────────────
const drawHeader = (doc, title, subtitle) => {
  doc.rect(0, 0, doc.page.width, 70).fill(DARK);
  doc.fillColor('#fff').fontSize(20).font('Helvetica-Bold').text('sahlearn', 40, 20);
  doc.fillColor(BRAND).fontSize(8).font('Helvetica').text('Admin Portal', 40, 44);
  doc.fillColor('#fff').fontSize(12).font('Helvetica-Bold').text(title, 160, 22, { align: 'right', width: doc.page.width - 200 });
  if (subtitle) {
    doc.fillColor('#87BAC2').fontSize(9).font('Helvetica').text(subtitle, 160, 40, { align: 'right', width: doc.page.width - 200 });
  }
  doc.moveDown(0);
  doc.y = 90;
};

// ── Section heading ──────────────────────────────────────────────────────────
const sectionHeading = (doc, text) => {
  doc.moveDown(0.6);
  doc.rect(40, doc.y, doc.page.width - 80, 20).fill(LIGHT);
  doc.fillColor(DARK).fontSize(9).font('Helvetica-Bold').text(text.toUpperCase(), 48, doc.y + 5);
  doc.moveDown(1.4);
};

// ── Info row ────────────────────────────────────────────────────────────────
const infoRow = (doc, label, value) => {
  const y = doc.y;
  doc.fillColor(GREY).fontSize(8).font('Helvetica').text(label, 40, y, { width: 130 });
  doc.fillColor(DARK).fontSize(9).font('Helvetica').text(value || '—', 175, y, { width: 350 });
  doc.moveDown(0.55);
};

// ── Table header ────────────────────────────────────────────────────────────
const tableHeader = (doc, cols) => {
  const y = doc.y;
  doc.rect(40, y, doc.page.width - 80, 18).fill(BRAND);
  let x = 48;
  for (const col of cols) {
    doc.fillColor('#fff').fontSize(8).font('Helvetica-Bold').text(col.label, x, y + 4, { width: col.width });
    x += col.width;
  }
  doc.moveDown(1.1);
};

// ── Table row ───────────────────────────────────────────────────────────────
const tableRow = (doc, cols, values, shade) => {
  const y = doc.y;
  if (shade) doc.rect(40, y - 2, doc.page.width - 80, 17).fill('#F7FAF9');
  let x = 48;
  for (let i = 0; i < cols.length; i++) {
    doc.fillColor(DARK).fontSize(8).font('Helvetica').text(String(values[i] ?? '—'), x, y, { width: cols[i].width });
    x += cols[i].width;
  }
  doc.moveDown(0.9);
};

// ── Footer ──────────────────────────────────────────────────────────────────
const drawFooter = (doc) => {
  const y = doc.page.height - 40;
  doc.rect(0, y - 8, doc.page.width, 48).fill(DARK);
  doc.fillColor('#87BAC2').fontSize(8).font('Helvetica')
    .text(`Generated by Sahlearn · ${new Date().toLocaleDateString('en-NG', { day: 'numeric', month: 'long', year: 'numeric' })}`, 40, y, { align: 'center', width: doc.page.width - 80 });
};

// ════════════════════════════════════════════════════════════════════════════
// STUDENT REPORT CARD
// ════════════════════════════════════════════════════════════════════════════
const generateReportCard = (res, { student, progress, attendance }) => {
  const doc = new PDFDocument({ size: 'A4', margin: 40, bufferPages: true });
  sendPDF(res, doc, `report-${student.studentId}.pdf`);

  drawHeader(doc, 'Student Report Card', new Date().toLocaleDateString('en-NG', { day: 'numeric', month: 'long', year: 'numeric' }));

  // Student info
  sectionHeading(doc, 'Student Information');
  infoRow(doc, 'Full Name', student.fullName);
  infoRow(doc, 'Student ID', student.studentId);
  infoRow(doc, 'Email', student.email);
  infoRow(doc, 'Academic Level', student.academicLevel || '—');
  infoRow(doc, 'Phone', student.phone || '—');

  // Academic performance per course
  for (const group of progress) {
    sectionHeading(doc, `Course: ${group.courseTitle}`);

    if (group.exams.length > 0) {
      doc.fillColor(GREY).fontSize(8).font('Helvetica-Bold').text('EXAMS', 48, doc.y);
      doc.moveDown(0.5);
      const examCols = [
        { label: 'Title', width: 200 },
        { label: 'Score', width: 70 },
        { label: 'Max', width: 70 },
        { label: '%', width: 60 },
        { label: 'Status', width: 80 },
      ];
      tableHeader(doc, examCols);
      group.exams.forEach((e, i) => {
        const pct = e.maxScore > 0 ? Math.round((e.score / e.maxScore) * 100) : 0;
        tableRow(doc, examCols, [e.title, e.score, e.maxScore, `${pct}%`, e.status === 'reviewed' ? 'Graded' : 'Pending'], i % 2 === 0);
      });
    }

    if (group.assignments.length > 0) {
      doc.moveDown(0.4);
      doc.fillColor(GREY).fontSize(8).font('Helvetica-Bold').text('ASSIGNMENTS', 48, doc.y);
      doc.moveDown(0.5);
      const asgCols = [
        { label: 'Title', width: 240 },
        { label: 'Score', width: 70 },
        { label: 'Max', width: 70 },
        { label: '%', width: 60 },
        { label: 'Status', width: 80 },
      ];
      tableHeader(doc, asgCols);
      group.assignments.forEach((a, i) => {
        const pct = a.score != null && a.maxScore > 0 ? Math.round((a.score / a.maxScore) * 100) : null;
        tableRow(doc, asgCols, [a.title, a.score ?? '—', a.maxScore, pct != null ? `${pct}%` : '—', a.status], i % 2 === 0);
      });
    }
  }

  // Attendance summary
  if (attendance.length > 0) {
    sectionHeading(doc, 'Attendance Summary');
    const attCols = [
      { label: 'Course', width: 240 },
      { label: 'Sessions', width: 80 },
      { label: 'Attended', width: 80 },
      { label: 'Attendance %', width: 100 },
    ];
    tableHeader(doc, attCols);
    attendance.forEach((a, i) => {
      tableRow(doc, attCols, [a.courseTitle, a.total, a.attended, a.percentage != null ? `${a.percentage}%` : '—'], i % 2 === 0);
    });
  }

  // Footer on last page
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    drawFooter(doc);
  }

  doc.end();
};

// ════════════════════════════════════════════════════════════════════════════
// ATTENDANCE REGISTER
// ════════════════════════════════════════════════════════════════════════════
const generateAttendanceRegister = (res, { session, roster }) => {
  const doc = new PDFDocument({ size: 'A4', margin: 40, bufferPages: true });
  const dateStr = new Date(session.date).toLocaleDateString('en-NG', { day: 'numeric', month: 'long', year: 'numeric' });
  sendPDF(res, doc, `attendance-${dateStr.replace(/ /g, '-')}.pdf`);

  drawHeader(doc, 'Attendance Register', `${session.course?.title || ''} · ${dateStr}`);

  sectionHeading(doc, session.label);

  if (session.note) {
    doc.fillColor(GREY).fontSize(8).font('Helvetica-Oblique').text(`Note: ${session.note}`, 48, doc.y);
    doc.moveDown(0.6);
  }

  const cols = [
    { label: '#', width: 30 },
    { label: 'Student ID', width: 100 },
    { label: 'Full Name', width: 220 },
    { label: 'Status', width: 80 },
    { label: 'Signature', width: 90 },
  ];
  tableHeader(doc, cols);

  roster.forEach((s, i) => {
    tableRow(doc, cols, [i + 1, s.studentCode, s.fullName, STATUS_LABEL[s.status] || s.status, ''], i % 2 === 0);
  });

  // Summary
  doc.moveDown(0.8);
  const counts = { present: 0, late: 0, excused: 0, absent: 0 };
  for (const s of roster) counts[s.status] = (counts[s.status] || 0) + 1;
  doc.fillColor(DARK).fontSize(9).font('Helvetica-Bold')
    .text(`Total: ${roster.length}   Present: ${counts.present}   Late: ${counts.late}   Excused: ${counts.excused}   Absent: ${counts.absent}`, 48, doc.y);

  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    drawFooter(doc);
  }

  doc.end();
};

// ════════════════════════════════════════════════════════════════════════════
// CSV helpers
// ════════════════════════════════════════════════════════════════════════════
const escapeCSV = (v) => {
  const s = String(v ?? '');
  return s.includes(',') || s.includes('"') || s.includes('\n') ? `"${s.replace(/"/g, '""')}"` : s;
};

const rowToCSV = (arr) => arr.map(escapeCSV).join(',');

const sendCSV = (res, filename, headers, rows) => {
  res.setHeader('Content-Type', 'text/csv');
  res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
  const lines = [rowToCSV(headers), ...rows.map(rowToCSV)].join('\r\n');
  res.send(lines);
};

module.exports = { generateReportCard, generateAttendanceRegister, sendCSV };
